name: "Hugo Deploy GitHub Pages"
author: "benmatselby"
description: "Build and deploy a hugo site to GitHub Pages"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "target"
  color: "purple"
inputs:
  go_version:
    description: "The version of Go to install. Go won't be installed if this isn't set."
    required: false
  hugo_args:
    description: "Any extra arguments to pass to Hugo."
    required: false
  hugo_extended:
    description: "If set to `true`, use the *extended* version of hugo."
    required: false
  hugo_publish_dir:
    description: "The publishDir from the hugo config.toml file"
    required: false
  hugo_version:
    description: "The version of hugo to use."
    required: true
